document.write("<p>Nombre del navegador: ");
document.write(informacion.nombre);
document.write("</p>");
document.write("<p>Idioma: ");
document.write(informacion.idioma);
document.write("</p>");
document.write("<p>VersiÃ³n: ");
document.write(informacion.version);
document.write("</p>");
document.write("<p>Plataforma: ");
document.write(informacion.plataforma);
document.write("</p>");
document.write("<p>Vendedor: ");
document.write(informacion.vendedor);
document.write("</p>");
document.write("<p>Agente: ");
document.write(informacion.agente);
document.write("</p>");
document.write("<p>Java activo: ");
document.write(informacion.javaActivo);
document.write("</p>");