document.write("<p>Informacion disponible de la asignatura</p>");
document.write("<p>Nombre: ");
document.write(asignatura.nombre);
document.write("</p>");
document.write("<p>Titulacion: ");
document.write(asignatura.titulacion);
document.write("</p>");
document.write("<p>Centro: ");
document.write(asignatura.centro);
document.write("</p>");
document.write("<p>Universidad: ");
document.write(asignatura.universidad);
document.write("</p>");
document.write("<p>Curso actual: ");
document.write(asignatura.curso);
document.write("</p>");
document.write("<p>Nombre: ");
document.write(asignatura.estudiante);
document.write("</p>");
document.write("<p>Email: ");
document.write(asignatura.email);
document.write("</p>");